version: 2

sources:
  - name: staging
    schema: sales_dataset_staging
    tables:
      - name: st_sales_data
        description: Sales data staging table

models:
  - name: dim_regions
    description: List of unique regions identified by region_id
    columns:
      - name: region_id
        data_type: int
        tests:
          - unique:
              severity: error
          - not_null:
              severity: error
        description: ID of the region
        
      - name: region_name
        data_type: string
        tests:
          - unique:
              severity: error
          - not_null:
              severity: error
        description: Name of the region


  