version: 2

sources:
  - name: staging
    schema: sales_dataset_staging
    tables:
      - name: st_sales_data
        description: Sales data staging table

models:
  - name: dim_regions
    description: List of unique regions identified by region_id
    columns:
      - name: region_id
        data_type: int
        tests:
          - unique:
              severity: error
          - not_null:
              severity: error
        description: ID of the region

      - name: region_name
        data_type: string
        tests:
          - unique:
              severity: error
          - not_null:
              severity: error
        description: Name of the region


  - name: dim_product_categories
    description: List of unique product categories identified by product_category_id
    columns:
      - name: product_category_id
        data_type: int
        tests:
        - unique:
            severity: error
        - not_null:
            severity: error
        description: ID of the product category

      - name: product_category_name
        data_type: string
        tests:
          - unique:
              severity: error
          - not_null:
              severity: error
        description: Name of the product category


  - name: dim_customer_types
    description: List of unique customer types identified by customer_type_id
    columns:
      - name: customer_type_id
        data_type: int
        tests:
        - unique:
            severity: error
        - not_null:
            severity: error
        description: ID of the customer type

      - name: customer_type_name
        data_type: string
        tests:
          - unique:
              severity: error
          - not_null:
              severity: error
        description: Name of the customer type
  

  - name: dim_payment_methods
    description: List of unique payment methods identified by payment_method_id
    columns:
      - name: payment_method_id
        data_type: int
        tests:
        - unique:
            severity: error
        - not_null:
            severity: error
        description: ID of the payment method

      - name: payment_method_name
        data_type: string
        tests:
          - unique:
              severity: error
          - not_null:
              severity: error
        description: Name of the payment method

  - name: dim_sales_channels
    description: List of unique sales channels identified by sales_channel_id
    columns:
      - name: sales_channel_id
        data_type: int
        tests:
        - unique:
            severity: error
        - not_null:
            severity: error
        description: ID of the sales channel

      - name: sales_channel_name
        data_type: string
        tests:
          - unique:
              severity: error
          - not_null:
              severity: error
        description: Name of the sales channel


  - name: dim_sales_reps
    description: List of unique sales representatives identified by sales_rep_id
    columns:
      - name: sales_rep_id
        data_type: int
        tests:
        - unique:
            severity: error
        - not_null:
            severity: error
        description: ID of the sales representative

      - name: sales_rep_name
        data_type: string
        tests:
          - unique:
              severity: error
          - not_null:
              severity: error
        description: Name of the sales representative


  
  